services:
  netops-bot:
    build: .
    network_mode: host
    volumes:
      - ./output:/app/output
      - ./bot_config.json:/app/bot_config.json
    environment:
      - TZ=Asia/Tokyo
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_DOMAIN=${CLOUDFLARE_DOMAIN}
      - ROUTER_IP=${ROUTER_IP}
      - ROUTER_USER=${ROUTER_USER}
      - ROUTER_PASS=${ROUTER_PASS}
      - DEBUG=${DEBUG}
    restart: unless-stopped
    container_name: netops-bot
    healthcheck:
      test: ["CMD", "pgrep", "-f", "discord_bot.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  output: